[pytest]
testpaths = test
python_files = test_*.py
addopts = --cov=entity --cov=process --cov=services  --cov-report=xml

[coverage:run]
branch = True
source = entity, services, process

[coverage:report]
show_missing = True
skip_covered = True

[coverage:xml]
output = coverage.xml