[pytest]
testpaths = test
python_files = test_*.py
addopts = --cov=db --cov=exception --cov-report=xml

[coverage:run]
branch = True
source = db,exception

[coverage:report]
show_missing = True
skip_covered = True

[coverage:xml]
output = coverage.xml