# Configuración general del proyecto
sonar.projectKey=db
sonar.projectName=db
sonar.projectVersion=1.0
sonar.sources=db,exception
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.pyo,**/*.pyd,**/tests/**,db/queries.py
sonar.sourceEncoding=UTF-8
sonar.language=python
sonar.python.version=3.12.3
sonar.tests=test
sonar.test.inclusions=**/test/**,**/test.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000/
sonar.token=sqp_1988d39d558edadd7ced8f9726049b8ae06365ef



