# Configuración general del proyecto
sonar.projectKey=complementaria_update
sonar.projectName=complementaria_update
sonar.projectVersion=1.0
sonar.sources=entity,process,services
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.pyo,**/*.pyd,**/tests/**,bd/db/queries.py,sql/*,attachments/*
sonar.sourceEncoding=UTF-8
sonar.language=python
sonar.python.version=3.12.3
sonar.tests=test
sonar.test.inclusions=**/test/**,**/test.py
sonar.python.coverage.reportPaths=coverage.xml
#sonar.host.url=http://localhost:9000/
#sonar.token=sqp_bb7e1ff8dd8373423f40f55dbef07069ede5bb14


